language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - composer install --no-interaction

script:
  - phpunit